DROP SCHEMA IF EXISTS BASICS_SCHEMA;

CREATE schema IF NOT EXISTS BASICS_SCHEMA;
USE BASICS_SCHEMA;

DROP TABLE IF EXISTS ABUELO;

CREATE TABLE ABUELO (
    ID INTEGER IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(256) NOT NULL,
    APELLIDOS VARCHAR(256) NOT NULL,
    FECHA DATE NOT NULL
);

DROP TABLE IF EXISTS AYUDANTE;

CREATE TABLE AYUDANTE (
    ID INTEGER IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(256) NOT NULL,
    APELLIDOS VARCHAR(256) NOT NULL,
    CORREO VARCHAR(100) DEFAULT NULL,
    ID_ABUELO INTEGER NOT NULL
);

DROP TABLE IF EXISTS USUARIO;

CREATE TABLE USUARIO (
	ID INTEGER IDENTITY PRIMARY KEY,
	USERNAME VARCHAR(45) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL
);
